### ISSUE TITLE
When .NET Core 3.1 installed, "Cannot compile typed context" error

### ISSUE THREAD

**Issue by sblom** [madd0/AzureStorageDriver#19]
When running LINQPad 6 (have tried both 6.5.5 and 6.6.1) with .NET Core 3.1 installed, I get an error when attempting to interact with connections that use the Azure Storage Driver:

> Error: Cannot compile typed context: Assuming assembly reference 'System.Runtime, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Madd0.AzureStorageDriver' matches identity 'System.Runtime, Version=4.2.2.0, Culture=neu

(the tooltip is truncated at that point)

If only netcore3.0 is installed, everything works fine.

If netcore3.1 and netcore3.0 are both installed, it fails. If only netcore3.1 is installed, it fails.

**Comment by madd0** [comment]
That's strange, I have both SDKs installed and have had LinqPad use both runtimes without any problems. The error sounds familiar though.
I'll try to take a look at it before going back to work on Monday, but for the moment, I can't reproduce

**Comment by sblom** [comment]
I wonder if it matters what version(s) were installed when I first made use of the driver. Let me try reinstalling the driver and some other things like that. Do you know much about how LINQPad handles dependency resolution for storage drivers?

**Comment by madd0** [comment]
As far as I know, in LinqPad 6, Nuget does all the dependency resolution.
What I have so far is that since the driver currently targets `netcoreapp3.0;net46`, I guess if only netcore3.1 is installed, it might be normal that it won't work. I'm guessing that, in a fresh environment, the driver shouldn't even install if only netcore3.1 is installed, but you're still seeing it from LinqPad's cache or something.
Best clue for now is to update the package to target both netcore3.0 and netcore3.1. I'll publish a new version on Nuget as soon as it's done ;)

**Comment by madd0** [comment]
@sblom new package published, let me know if it solves the problem 😉
